apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-exporter
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama-exporter
  template:
    metadata:
      labels:
        app: ollama-exporter