apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-exporter
  namespace: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama-exporter
  template:
    metadata:
      labels:
        app: ollama-exporter
    spec:
      containers:
        - livenessProbe:
            httpGet:
              path: /metrics
              port: 8000
            initialDelaySeconds: 10
            failureThreshold: 3
            periodSeconds: 15
        
          readinessProbe:
            httpGet:
              path: /metrics
              port: 8000
            initialDelaySeconds: 5
            failureThreshold: 3
            periodSeconds: 5
        
          name: ollama-exporter
          image: 192.168.0.22:30964/ollama-exporter:latest
          ports:
            - containerPort: 8000
          env:
            - name: OLLAMA_HOST
              value: http://ollama.ollama.svc.cluster.local:11434
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"