apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ollama-exporter
  namespace: default
spec:
  selector:
    matchLabels:
      app: ollama-exporter
  endpoints:
    - port: 9464
      interval: 15s
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_node_name]