apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ollama-exporter
  namespace: monitoring
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - ollama
  selector:
    matchLabels:
      app: ollama-exporter
  endpoints:
    - port: http
      interval: 15s
      path: /metrics
