apiVersion: v1
kind: Service
metadata:
  name: ollama-exporter
  namespace: ollama
  labels:
    app: ollama-exporter
spec:
  selector:
    app: ollama-exporter
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: ClusterIP
